// Assuming this is the content of the file with the necessary changes
// other lines...
const conversationManager = {
  // other parameters...
  model: 'gpt-3.5-turbo', // Changed from 'gpt-4' to 'gpt-3.5-turbo'
  // other parameters...
};
// other lines...